apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-deployment
spec:
  selector:
    matchLabels:
      app: boardgame
  replicas: 2
  template:
    metadata:
      labels:
        app: boardgame
    spec:
      containers:
        - name: boardgame
          image: adijaiswal/boardshack:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080  # The port that the container is running on in the cluster

  # Port on each node that the service will listen on
---
apiVersion: v1
kind: Service
metadata:
  name: boardgame-ssvc
spec:
  selector:
    app: boardgame
  type: NodePort
  ports:
    - port: 80             # Port exposed by the service
      targetPort: 8080     # Port on which the container is listening
      nodePort: 30001    
